export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const UPDATE_FAVORITE_QUANTITY = "UPDATE_FAVORITE_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const ADD_MULTIPLE_TO_FAVORITES ="ADD_MULTIPLE_TO_FAVORITES";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
